export const Routes = {
  root: '/',

  login: '/login',
  dashboard: '/dashboard',
  roles: '/dashboard/roles',
  admins: '/dashboard/admins',
  banners: '/dashboard/banners',
  categories: '/dashboard/categories',
  warehouses: '/dashboard/warehouses',
  regions: '/dashboard/regions',
  cities: '/dashboard/cities',
  settings: '/dashboard/settings',
  shippingMethods: '/dashboard/shipping-methods',
  products: '/dashboard/products',
  coupons: '/dashboard/coupons',
  aboutUs: '/dashboard/about-us',
  customers: '/dashboard/customers',
  customerDetail: '/dashboard/customers/:id',
  customerDetailPath: (id: number) => `/dashboard/customers/${id}`,
  reviews: '/dashboard/reviews',
  productNew: '/dashboard/products/new',
  productEdit: '/dashboard/products/:id/edit',
  productEditPath: (id: number) => `/dashboard/products/${id}/edit`,
  errors: {
    unAuthorized: '/401',
    forbidden: '/403',
    internalServerError: '/500',
    maintenanceError: '/maintenance',
    notFound: '*',
  },
} as const
