export const Routes = {
  root: '/',

  login: '/login',
  dashboard: '/dashboard',
  orders: '/dashboard/orders',
  orderDetail: '/dashboard/orders/:id',
  orderDetailPath: (id: number) => `/dashboard/orders/${id}`,
  roles: '/dashboard/roles',
  admins: '/dashboard/admins',
  banners: '/dashboard/banners',
  categories: '/dashboard/categories',
  warehouses: '/dashboard/warehouses',
  regions: '/dashboard/regions',
  cities: '/dashboard/cities',
  settings: '/dashboard/settings',
  shippingMethods: '/dashboard/shipping-methods',
  products: '/dashboard/products',
  coupons: '/dashboard/coupons',
  aboutUs: '/dashboard/about-us',
  customers: '/dashboard/customers',
  customerDetail: '/dashboard/customers/:id',
  customerDetailPath: (id: number) => `/dashboard/customers/${id}`,
  reviews: '/dashboard/reviews',
  testimonials: '/dashboard/testimonials',
  staticPages: '/dashboard/pages',
  staticPageNew: '/dashboard/pages/new',
  staticPageEdit: '/dashboard/pages/:id/edit',
  staticPageEditPath: (id: number) => `/dashboard/pages/${id}/edit`,
  productNew: '/dashboard/products/new',
  productEdit: '/dashboard/products/:id/edit',
  productEditPath: (id: number) => `/dashboard/products/${id}/edit`,
  errors: {
    unAuthorized: '/401',
    forbidden: '/403',
    internalServerError: '/500',
    maintenanceError: '/maintenance',
    notFound: '*',
  },
} as const
